name: Node

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  message_uploader_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.10"

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Run tests with coverage
        working-directory: .
        run: npm run test
